### ISSUE TITLE
Negative duration can be entered in the "Add New Task" form

### ISSUE THREAD

**Issue by guswawan** [ahmadrosid/timeboxing#1]
Currently, the "Add New Task" form allows users to input negative values in the duration field. This is inconsistent with the concept of timeboxing and can cause problems in time calculations.

Steps to reproduce:
1. Open the main page of the application
2. In the "Add New Task" section, enter a task name (e.g., "Test Task")
3. In the duration field, enter a negative value (e.g., -5)
4. Click the "Add Task" button

<img width="1221" alt="image" src="https://github.com/user-attachments/assets/4e34f956-a7ff-4fb6-b0b9-fa20bf65b445">

Proposed solution:
We could add validation or disallow negative values to the duration input to ensure only positive values are accepted. 

Am I allowed to work on this fix?

**Comment by ahmadrosid** [comment]
Yes sounds good to me go ahead.
